version: '3.8'

services:

  vote:
    build: 
      context: ./vote
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    depends_on:
      - redis

  worker:
    build: 
      context: ./worker
      dockerfile: Dockerfile
    volumes:
      - .:/code
    depends_on:
      - redis
      - db

  result:
    build: 
      context: ./result
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - .:/code
    depends_on:
      - db

  redis:
    container_name: redis
    image: redis:alpine

  db:
    container_name: db
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres