apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    name: postgres-svc
    app: voting-app
spec:
  selector:
    name: postgres-app
    app: voting-app
  ports:
  - port: 5432
    targetPort: 5432