apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: myapp
    app: voting-app
spec:
  selector:
    name: redis-app
    app: voting-app
  ports:
  - port: 6379
    targetPort: 6379
