apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      name: redis-app
      app: voting-app

  template:
    metadata:
  name: redis-pod
  labels:
    name: redis-app
    app: voting-app

  spec:
    containers:
      - name: redis
        image: redis
        ports:
           - containerPort: 6379