apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      name: result-app-pod
      app: voting-app
  template:
    metadata:
      name: result-app-pod
      labels:
        name: result-app-pod
        app: voting-app
  spec:
    containers:
      - name: result-app
        image: kodekloud/examplevotingapp_result:v1
        ports:
          - containerPort: 80