apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: result-pdb
  labels:
    app.kubernetes.io/name: result
    app.kubernetes.io/component: dashboard
    app.kubernetes.io/part-of: voting-app
    app.kubernetes.io/managed-by: kustomize
spec:
  minAvailable: 1

  selector:
    matchLabels:
      app.kubernetes.io/name: result
      app.kubernetes.io/part-of: voting-app
