apiVersion: v1
kind: Service
metadata:
  name: result_service
spec:
  selector:
    app: voting-app
    type: result-app
  ports:
  - port: 4000
    targetPort: 4000
    nodePort: 30006
  type: NodePort