apiVersion: apps/v1 
kind: Deployment
metadata:
  name: vote-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voting-app
      type: vote-app
  template:
    metadata:
      name: vote-pod
      labels:
        app: voting-app
        type: vote-app
    spec:
      containers:
      - name: vote
        image: 817780818534.dkr.ecr.us-east-1.amazonaws.com/vote:latest
        ports:
        - containerPort: 8000