apiVersion: apps/v1 
kind: Deployment
metadata:
  name: worker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voting-app
      type: worker-app
  template:
    metadata:
      name: worker-pod
      labels:
        app: voting-app
        type: worker-app
    spec:
      containers:
      - name: worker
        image: 817780818534.dkr.ecr.us-east-1.amazonaws.com/worker:latest